var JSON_VATGIA;JSON_VATGIA||(JSON_VATGIA={});var MYAD_COOKIE_ALW_NAME="__utmalw";function myad_setcookie(b,a,d){var c=new Date,d=c.getTime()+1E3*(d+25200);c.setTime(d);document.cookie=b+"="+a+";expires="+c.toUTCString()+";path=/"}function myad_getcookie(b){var a,d,c,e=document.cookie.split(";");for(a=0;a<e.length;a++)if(d=e[a].substr(0,e[a].indexOf("=")),c=e[a].substr(e[a].indexOf("=")+1),d=d.replace(/^\s+|\s+$/g,""),d==b)return unescape(c)}
function myad_erase_cookie(b){myad_setcookie(b,"",-1E3)}
(function(){function b(a){return 10>a?"0"+a:a}function a(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=h[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(b,c){var e,m,l,h,n=g,j,f=c[b];f&&"object"===typeof f&&"function"===typeof f.toJSON&&(f=f.toJSON(b));"function"===typeof i&&(f=i.call(c,b,f));switch(typeof f){case "string":return a(f);case "number":return isFinite(f)?""+f:"null";case "boolean":case "null":return""+
f;case "object":if(!f)return"null";g+=k;j=[];if("[object Array]"===Object.prototype.toString.apply(f)){h=f.length;for(e=0;e<h;e+=1)j[e]=d(e,f)||"null";l=0===j.length?"[]":g?"[\n"+g+j.join(",\n"+g)+"\n"+n+"]":"["+j.join(",")+"]";g=n;return l}if(i&&"object"===typeof i){h=i.length;for(e=0;e<h;e+=1)"string"===typeof i[e]&&(m=i[e],(l=d(m,f))&&j.push(a(m)+(g?": ":":")+l))}else for(m in f)Object.prototype.hasOwnProperty.call(f,m)&&(l=d(m,f))&&j.push(a(m)+(g?": ":":")+l);l=0===j.length?"{}":g?"{\n"+g+j.join(",\n"+
g)+"\n"+n+"}":"{"+j.join(",")+"}";g=n;return l}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var c=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,k,h={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;"function"!==typeof JSON_VATGIA.stringify&&(JSON_VATGIA.stringify=function(a,b,e){var c;k=g="";if(typeof e==="number")for(c=0;c<e;c=c+1)k=k+" ";else typeof e==="string"&&(k=e);if((i=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON_VATGIA.stringify");
return d("",{"":a})});"function"!==typeof JSON_VATGIA.parse&&(JSON_VATGIA.parse=function(a,b){function e(a,c){var d,g,f=a[c];if(f&&typeof f==="object")for(d in f)if(Object.prototype.hasOwnProperty.call(f,d)){g=e(f,d);g!==void 0?f[d]=g:delete f[d]}return b.call(a,c,f)}var d,a=""+a;c.lastIndex=0;c.test(a)&&(a=a.replace(c,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){d=eval("("+a+")");return typeof b==="function"?e({"":d},""):d}throw new SyntaxError("JSON_VATGIA.parse");})})();
var Base64_vatgia={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(b){for(var a="",d,c,e,g,k,h,i=0,b=Base64_vatgia._utf8_encode(b);i<b.length;)d=b.charCodeAt(i++),c=b.charCodeAt(i++),e=b.charCodeAt(i++),g=d>>2,d=(d&3)<<4|c>>4,k=(c&15)<<2|e>>6,h=e&63,isNaN(c)?k=h=64:isNaN(e)&&(h=64),a=a+this._keyStr.charAt(g)+this._keyStr.charAt(d)+this._keyStr.charAt(k)+this._keyStr.charAt(h);return a},_utf8_encode:function(b){for(var b=b.replace(/\r\n/g,"\n"),a="",d=0;d<
b.length;d++){var c=b.charCodeAt(d);128>c?a+=String.fromCharCode(c):(127<c&&2048>c?a+=String.fromCharCode(c>>6|192):(a+=String.fromCharCode(c>>12|224),a+=String.fromCharCode(c>>6&63|128)),a+=String.fromCharCode(c&63|128))}return a}};"undefined"==typeof check_show_advatgia&&(check_show_advatgia=0);Object.vgsize=function(b){var a=0,d;for(d in b)b.hasOwnProperty(d)&&a++;return a};
function vatgiaAd(b,a){var d="http://ad.vatgia.com/";"undefined"!=typeof is_local&&(d="http://localhost:9013/");this.pageOptions=b;"underfined"==typeof this.pageOptions.is_mobile&&(this.pageOptions.is_mobile=navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)||navigator.userAgent.match(/Mobile Safari/i)?
1:0);var c=myad_getcookie(MYAD_COOKIE_ALW_NAME);0<parseInt(c)?(this.pageOptions.close_box_id=parseInt(c),myad_erase_cookie(MYAD_COOKIE_ALW_NAME)):this.pageOptions.close_box_id=0;for(key in a)a[key].div_show_exists=0,"undefined"!=a[key].divIdShow&&(c=document.getElementById(a[key].divIdShow),null!=c&&(a[key].div_show_exists=1));if(b.banners&&"object"==typeof b.banners)for(key in b.banners)b.banners[key].divIdShow&&""!=b.banners[key].divIdShow&&(c=document.getElementById(b.banners[key].divIdShow),null==
c&&delete b.banners[key]);this.adblock=a;this.Ads=function(){if(typeof this.pageOptions.keyword!="undefined")this.pageOptions.keyword=Base64_vatgia.encode(this.pageOptions.keyword);var a=window.location.hash;this.pageOptions.myad_for_example=a!="undefined"&&a!=""&&a=="#myad_for_example"?1:0;if(a!="undefined"&&a!=""&&a.search("/myadBanner/")>-1)this.pageOptions.myadBanner_example=a;if(check_show_advatgia!=1){check_show_advatgia=1;var b=JSON_VATGIA.stringify(this.pageOptions),b=Base64_vatgia.encode(b),
c=JSON_VATGIA.stringify(this.adblock),c=Base64_vatgia.encode(c);if(Object.vgsize(this.adblock)>0||Object.vgsize(this.pageOptions.banners)>0){element=document.getElementById("advatgia-urlad");element!=null&&element.parentNode.removeChild(element);var h=0;typeof jQuery!="undefined"&&(h=1);a=document.createElement("script");a.type="text/javascript";a.id="advatgia-urlad";a.src=d+"jsv2/advatgia.php?option="+b+"&block="+c+"&jquery="+h;b=document.getElementsByTagName("script");b[0].parentNode.insertBefore(a,
b[0])}}}}(function(){"undefined"==typeof adblock&&(adblock={});"undefined"==typeof pageOptions&&(pageOptions={});(new vatgiaAd(pageOptions,adblock)).Ads();adVatgiaLoad=!0})();
